### ISSUE TITLE
Fails to build on 1.65

### ISSUE THREAD

**Issue by cavemanloverboy** [alecmocatta/serde_traitobject#32]
On a fresh cargo bin project, adding `serde_traitobject = "0.2.7"` and running `cargo +nightly build` fails.

**Comment by shouc** [comment]
Error log:
```

error[E0059]: type parameter to bare `std::ops::FnOnce` trait must be a tuple
   --> /Users/shou/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_traitobject-0.2.7/src/convenience.rs:154:16
    |
154 |     type Output = F::Output;
    |                   ^^^^^^^^^ the trait `Tuple` is not implemented for `A`
    |
note: required by a bound in `std::ops::FnOnce`
   --> /Users/shou/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:499:24
    |
499 | pub trait FnOnce<Args: Tuple> {
    |                        ^^^^^ required by this bound in `std::ops::FnOnce`
help: consider further restricting type parameter `A`
    |
152 |     F: FnOnce<A>, A: std::marker::Tuple
    |                 ~~~~~~~~~~~~~~~~~~~~~~~

error[E0277]: functions with the "rust-call" ABI must take a single non-self tuple argument
   --> /Users/shou/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_traitobject-0.2.7/src/convenience.rs:155:2
    |
155 |     extern "rust-call" fn call_once(self, args: A) -> Self::Output {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Tuple` is not implemented for `A`
    |
help: consider further restricting type parameter `A`
    |
152 |     F: FnOnce<A>, A: std::marker::Tuple
    |                 ~~~~~~~~~~~~~~~~~~~~~~~

error[E0277]: functions with the "rust-call" ABI must take a single non-self tuple argument
   --> /Users/shou/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_traitobject-0.2.7/src/convenience.rs:163:2
    |
163 |     extern "rust-call" fn call_mut(&mut self, args: A) -> Self::Output {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Tuple` is not implemented for `A`
    |
help: consider further restricting type parameter `A`
    |
161 |     F: FnMut<A>, A: std::marker::Tuple
    |                ~~~~~~~~~~~~~~~~~~~~~~~

error[E0277]: functions with the "rust-call" ABI must take a single non-self tuple argument
   --> /Users/shou/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_traitobject-0.2.7/src/convenience.rs:171:2
    |
171 |     extern "rust-call" fn call(&self, args: A) -> Self::Output {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Tuple` is not implemented for `A`
    |
help: consider further restricting type parameter `A`
    |
169 |     F: Fn<A>, A: std::marker::Tuple
    |             ~~~~~~~~~~~~~~~~~~~~~~~


```

**Comment by alecmocatta** [comment]
Thanks for the report! Should be a pretty straightforward PR if you're open to fixing it? Think it's just a matter of adding `A: Tuple` to the bounds, per the compiler's advice.

**Comment by syntheticore** [comment]
Hey @alecmocatta, would you mind merging #33 and updating the crate? :)

**Comment by alecmocatta** [comment]
Published as v0.2.8

**Comment by syntheticore** [comment]
Awesome, thanks!
